<?php

namespace BeTeen\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function findAllSubcategories($parent)
	{
		$builder = $this->createQueryBuilder('c');
		$builder->where('c.categorieParente = :parent')
				->setParameter("parent",$parent)
				->orderBy("c.nom");
		return $builder->getQuery()->getResult();
	}
}
