<?php

namespace BeTeen\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SujetVersusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetVersusRepository extends EntityRepository
{
}
