<?php

namespace BeTeen\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SujetStandardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetStandardRepository extends EntityRepository
{
    public function findOneSubjectSlug($slug)
    {
        $builder = $this->createQueryBuilder('s')
						->leftJoin('s.reponses','r')
						->addSelect('r');
        
	$builder->where('s.slug = :slug')
			->setParameter("slug",$slug)
			->orderBy("r.date");
        
	return $builder->getQuery()->getOneOrNullResult();
        
    }
}
