security:
    encoders:
        BeTeen\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 2
            encode_as_base64: false
        
    role_hierarchy:
        ROLE_MODERATEUR:        ROLE_USER
        ROLE_ADMIN:             [ROLE_USER,ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN:       [ROLE_USER,ROLE_ADMIN,ROLE_MODERATEUR,ROLE_ALLOWED_TO_SWITCH]
        
    
    providers:
        main:
            entity: { class: BeTeen\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:            ^/
            anonymous:          true
            provider:           main
            form_login:
                login_path:     login
                check_path:    login_check
            logout:
                path:           logout
                target:         /
            remember_me:
                key:            "%secret%"
                lifetime:       604800 #7 jours en secondes
                path:           /
                domain:         ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }