security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    role_hierarchy:
        ROLE_MODERATEUR:        ROLE_USER
        ROLE_ADMIN:             [ROLE_USER,ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN:       [ROLE_USER,ROLE_ADMIN,ROLE_MODERATEUR,ROLE_ALLOWED_TO_SWITCH]
        
    
    providers:
        in_memory:
            memory: 
                users:
                    user:   {password: userpass, roles:["ROLE_USER"]}
                    modo:   {password: modopass, roles:["ROLE_MODERATEUR"]}
                    admin:  {password: adminpass, roles:["ROLE_ADMIN"]}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:            ^/
            anonymous:          true
            provider:           in_memory
            form_login:
                login_path:     login
                check_path:    login_check
            logout:
                path:           logout
                target:         /
