be_teen_user_profil:
    path:     /profil/{usr}
    defaults:  { _controller: BeTeenUserBundle:User:Profil }

be_teen_user_register:
    path:     /enregistrement
    defaults: { _controller: BeTeenUserBundle:User:Register }